use ozmxv751nx7f9n4v;
drop table if exists Product;

CREATE TABLE Product (
    Id INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (Id),
    CollectonId INT,
    FOREIGN KEY (CollectonId)
        REFERENCES Collection (Id),
    Name VARCHAR(100),
    FriendlyName VARCHAR(100),
    ImgSrc VARCHAR(100),
    Price VARCHAR(100)
);

insert into Product (CollectonId, ImgSrc, FriendlyName, Price) values (1,"assets/img/WeddingBand.jpg", "Eternity Wedding Band", "Price: 650"),
            (1,"assets/img/WeddingBands.jpg", "Oravo Wedding Band", "Price: 500"),
            (1,"assets/img/weddingBand3.jpg", "Kendra Scott Wedding Ring", "Price: 600"),
            (1,"assets/img/weddingBand4.jpg", "Monarch Wedding Band", "Price: 2,000"),
            (1,"assets/img/WeddingBand2.jpg", "14k Gold Wedding Band", "Price: 1,500"),
            (1,"assets/img/WeddingBand5.jpg", "Luxurman Wedding Band", "Price: 2,000"),
            (1,"assets/img/WeddingBand6.jpg", "Cavalier Wedding Band", "Price: 3,000"),
            (1,"assets/img/WeddingBand7.jpg", "Manly Bands", "Price: 1,000"),
            (2,"assets/img/earring.jpg", "Stud Earrings", "Price: 4,000"),
            (2,"assets/img/earring2.jpg", "London Blue Topaz and Diamond Earing", "Price: 5,000"),
            (2,"assets/img/earring3.jpg", "Stud Halo Earrings", "Price: 5,500"),
            (2,"assets/img/earring4.jpg", "Duis aute irure", "Price: 7,500"),
            (2,"assets/img/earring5.jpg", "Yolana Diamond Earrings", "Price: 4,500"),
            (2,"assets/img/earring6.jpg", "Blue Nile Diamond Earrings", "Price: 5,000"),
            (2,"assets/img/earring7.jpg", "Drop Swirl Diamond Earring", "Price: 6,000"),
            (2,"assets/img/earring8.jpg", "Antique Drop Diamond Earrings", "Price: 3,000"),
            (3,"assets/img/Jan-birthStone.jpg", "January Birthstone", "Price: 500"),
            (3,"assets/img/feb-birthStone.jpg", "February Birthstone", "Price: 500"),
            (3,"assets/img/Mar-birthStone.jpg", "March Birthstone", "Price: 550"),
            (3,"assets/img/April-birthStone.jpg", "April Birthstone", "Price: 750"),
            (3,"assets/img/Sep-birthStone.jpg", "September Birthstone", "Price: 450"),
            (3,"assets/img/Oct-birthStone.jpg", "October Birthstone", "Price: 300"),
            (3,"assets/img/nov-birthStone.jpg", "November Birthstone", "Price: 600"),
            (3,"assets/img/dec-birthStone.jpg", "December Birthstone", "Price: 800"),
            (4,"assets/img/claddagh.jpg", "Claddagh Ring", "Price: 400"),
            (4,"assets/img/claddagh2.jpg", "Claddagh Ring", "Price: 500"),
            (4,"assets/img/claddagh3.jpg", "Claddagh Ring", "Price: 550"),
            (4,"assets/img/claddagh4.jpg", "Claddagh Ring", "Price: 750"),
            (4,"assets/img/claddagh5.jpg", "Claddagh Ring", "Price: 400"),
            (4,"assets/img/claddagh6.jpg", "Claddagh Ring", "Price: 500"),
            (4,"assets/img/claddagh7.jpg", "Claddagh Ring", "Price: 600"),
            (4,"assets/img/claddagh8.jpg", "Claddagh Ring", "Price: 300"),
            (5,"assets/img/paveRing.jpg", "Pave Engagement Ring", "Price: 4,000"),
            (5,"assets/img/paveRing2.jpg", "Pave Engagement Ring", "Price: 5,000"),
            (5,"assets/img/paveRing3.jpg", "Pave Engagement Ring", "Price: 5,500"),
            (5,"assets/img/paveRing4.jpg", "Pave Engagement Ring", "Price: 7,500"),
            (5,"assets/img/paveRing5.jpg", "Pave Engagement Ring", "Price: 4,500"),
            (5,"assets/img/paveRing6.jpg", "Pave Engagement Ring", "Price: 5,000"),
            (5,"assets/img/paveRing7.jpg", "Pave Engagement Ring", "Price: 6,000"),
            (5,"assets/img/paveRing8.jpg", "Pave Engagement Ring", "Price: 3,000"),
            (6,"assets/img/solitareRing.jpg", "Solitare Engagement Ring ", "Price: 4,000"),
            (6,"assets/img/solitareRing2.jpg", "Solitare Engagement Ring ", "Price: 5,000"),
            (6,"assets/img/solitareRing3.jpg", "Solitare Engagement Ring ", "Price: 5,500"),
            (6,"assets/img/solitareRing4.jpg", "Solitare Engagement Ring ", "Price: 7,500"),
            (6,"assets/img/solitareRing5.jpg", "Solitare Engagement Ring ", "Price: 4,500"),
            (6,"assets/img/solitareRing6.jpg", "Solitare Engagement Ring ", "Price: 5,000"),
            (6,"assets/img/solitareRing7.jpg", "Solitare Engagement Ring ", "Price: 6,000"),
            (6,"assets/img/solitareRing8.jpg", "Solitare Engagement Ring ", "Price: 3,000"),
            (7,"assets/img/tensionSet.jpg", "Tension Set Engagement Ring ", "Price: 4,000"),
            (7,"assets/img/tensionSet2.jpg", "Tension Set Engagement Ring ", "Price: 5,000"),
            (7,"assets/img/tensionSet3.jpg", "Tension Set Engagement Ring ", "Price: 5,500"),
            (7,"assets/img/tensionSet4.jpg", "Tension Set Engagement Ring ", "Price: 7,500"),
            (7,"assets/img/tensionSet5.jpg", "Tension Set Engagement Ring ", "Price: 4,500"),
            (7,"assets/img/tensionSet6.jpg", "Tension Set Engagement Ring ", "Price: 5,000"),
            (7,"assets/img/tensionSet7.jpg", "Tension Set Engagement Ring ", "Price: 6,000"),
            (7,"assets/img/tensionSet8.jpg", "Tension Set Engagement Ring ", "Price: 3,000"),
            (8,"assets/img/haloRing.jpg", "Halo Engagement Ring", "Price: 4,000"),
            (8,"assets/img/haloRing2.jpg", "Halo Engagement Ring", "Price: 5,000"),
            (8,"assets/img/haloRing3.jpg", "Halo Engagement Ring", "Price: 5,500"),
            (8,"assets/img/haloRing4.jpg", "Halo Engagement Ring", "Price: 7,500"),
            (8,"assets/img/haloRing5.jpg", "Halo Engagement Ring", "Price: 4,500"),
            (8,"assets/img/haloRing6.jpg", "Halo Engagement Ring", "Price: 5,000"),
            (8,"assets/img/haloRing7.jpg", "Halo Engagement Ring", "Price: 6,000"),
            (8,"assets/img/haloRing8.jpg", "Halo Engagement Ring", "Price: 3,000")
